---
# tasks file for oh-my-zsh
- import_tasks: base.yml
- name: Replace default zsh plugins
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins'
    line: plugins=(git)
- name: change user shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh