---
# tasks file for oh-my-zsh
- name: Install git zsh
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - git
    - zsh
    - vim

- name: Clone oh-my-zsh repo
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    version: master
- name: Zshrc
  ansible.builtin.copy:
    src: '~/.oh-my-zsh/templates/zshrc.zsh-template'
    dest: '~/.zshrc'
    mode: '0644'
    remote_src: yes
    force: no
- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh