---
# tasks file for oh-my-zsh
- name: install git zsh
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - git
    - zsh
    - vim

- name: clone oh-my-zsh repo
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    version: master
- name: zshrc
  copy:
    src: '~/.oh-my-zsh/templates/zshrc.zsh-template'
    dest: '~/.zshrc'
    remote_src: yes
    force: no
- name: change user shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh