name: Ansible-Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - test
      - create-workflow/*
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version:
          - "3.6"
    steps:
      - uses: actions/checkout@v2.1.0
        # with:
        #   path: molecule_demo
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: check yaml linting
        run: yamllint .
      - name: check ansible lint
        run: ansible-lint
      - name: set ansible config
        run: printf '[defaults]\nroles_path=../' >ansible.cfg
      - name: ansible syntax-check
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
      - name: Run docker ${{matrix.version}} test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
